import { combineReducers } from 'redux'
import {
  evaluacionInfoReducer, 
  evaluacionAgregadoReducer, 
  evaluacionResumenReducer, 
  evaluacionCalculoReducer, 
  evaluacionCorreccionUpdateReducer, 
  evaluacionCorreccionDeleteReducer,
  evaluacionCorreccionGlobalUpdateReducer, 
  evaluacionCorreccionGlobalDeleteReducer, 
  evaluacionValidacionUpdateReducer, 
  evaluacionSupervisionUpdateReducer, 
  evaluacionCurrentReducer,
  evaluacionSupervisionMasivaReducer,
  evaluacionValidacionMasivaReducer,
  evaluacionFinalizarSupervisionReducer,
  evaluacionFinalizarValidacionReducer,
  evaluacionInfoInformeReducer, 
  evaluacionResumenInformeReducer,
} from './evaluacionReducer'
import {
  userLoginReducer,
  userAvisosReducer,
  userRegisterReducer,
  userDetailsReducer,
  userDeleteReducer,
  userUpdateReducer,
  userListReducer,
  refreshTokenReducer,
  userListByRoleNameReducer,
  userGetProfileInfoeReducer,
  userListResponsiblesReducer,
  userListValidatorsReducer,
  userListByProfileIdReducer,
  userGetFavoritesReducer,
  userRegisterFavoritesReducer,
} from './userReducers'
import {
  logRegisterReducer,
  logListReducer,
  logDetailsReducer,
  logDeleteReducer,
  logDeleteManyReducer,
} from './logReducers'
import { sendEMailReducer } from './sendEMailReducers'

import {dashboardReducer} from './dashboardReducer'

import { unitDeleteReducer,
   unitListReducer,
   unitRegisterReducer,
   unitUpdateReducer,
   unitRelatedListReducer,
} from './unitReducers'
import { festivosDeleteReducer, festivosListReducer, festivosRegisterReducer, festivosUpdateReducer } from './festivosReducers'
import { 
  configuracionDeleteReducer, 
  configuracionListReducer, 
  configuracionRegisterReducer, 
  configuracionUpdateReducer,
  configuracionHistoricalListReducer,
} from './configuracionReducers'
import {
  subdirectionDeleteReducer,
  subdirectionListReducer,
  subdirectionRegisterReducer,
  subdirectionUpdateReducer,
  subdirectionRelatedListReducer
} from './subdirectionReducer'
import {
  departamentDeleteReducer,
  departamentListReducer,
  departamentRegisterReducer,
  departamentUpdateReducer,
  departamentRelatedListReducer,
} from './departamentReducer'
import { 
   roleDeleteReducer, 
   roleListReducer, 
   roleRegisterReducer, 
   roleUpdateReducer,
   roleRelatedListReducer,
} from './roleReducer'
import {
  serviceDeleteReducer,
  serviceListReducer,
  serviceRegisterReducer,
  serviceUpdateReducer,
  serviceRelatedListReducer,
} from './serviceReducer'
import {
  taskTypeDeleteReducer,
  taskTypeListReducer,
  taskTypeRegisterReducer,
  taskTypeUpdateReducer,
} from './taskTypeReducer'
import {
  profileDeleteReducer,
  profileListReducer,
  profileRegisterReducer,
  profileUpdateReducer,
  profileByPositionListReducer,
} from './profileReducer'
import {
  taskDeleteReducer,
  taskListReducer,
  taskRegisterReducer,
  taskUpdateReducer,
  taskListByProfileReducer,
  handleDuplicateTaskReducer,
  taskByIdReducer,
} from './taskReducer'
import {
  permissionDeleteReducer,
  permissionListReducer,
  permissionRegisterReducer,
  permissionUpdateReducer,
} from './permissionReducer'
import {
  profileToManagerDeleteReducer,
  profileToManagerListReducer,
  profileToManagerRegisterReducer,
  profileToManagerUpdateReducer,
} from './profileToManagerReducer'
import {
  taskAbsenceDeleteReducer,
  taskAbsenceListReducer,
  taskAbsenceRegisterReducer,
  taskAbsenceUpdateReducer,
} from './taskAbsenceReducer'
import {
  taskGeneralDeleteReducer,
  taskGeneralListReducer,
  taskGeneralRegisterReducer,
  taskGeneralUpdateReducer,
} from './taskGeneralReducer'
import {
  taskOtherDeleteReducer,
  taskOtherListReducer,
  taskOtherRegisterReducer,
  taskOtherUpdateReducer,
  taskHistoricalListReducer,
  taskProfilesReducer,
} from './taskOtherReducer'
import {
  taskSpecificDeleteReducer,
  taskSpecificListReducer,
  taskSpecificRegisterReducer,
  taskSpecificUpdateReducer,
  taskSpecificByUserReducer,
} from './taskSpecificReducer'
import {
  userPermissionDeleteReducer,
  userPermissionListReducer,
  userPermissionRegisterReducer,
  userPermissionUpdateReducer,
} from './userPermissionReducers'

import {
  teamWorkListReducer,
  teamWorkDeleteReducer,
  teamWorkUpdateReducer,
  teamWorkListByRoleReducer,
  teamWorksByResponsibleReducer,
  teamWorksByValidatorReducer,
  teamWorkRegisterByResponsibleReducer,
  teamWorkRegisterByValidatorReducer,
  teamWorkRegisterByPermissionReducer,
  teamWorkHistoricalListReducer,
} from './teamWorkReducer'

import {
  activitiesListReducer,
  activityInfoReducer,
  activitiesRegisterReducer,
  activitiesUpdateReducer,
  activitiesDeleteReducer,
  activitiesListByJobPositionIdReducer,
} from './activitiesReducer'

import { uiMultiTaskReducer } from './uiMultiTaskReducer'

import {
  objetiveAbsenceRegisterReducer,
  objetivesAbsencesListReducer,
  objetivesAbsencesDeleteReducer,
  objetivesAbsencesUpdateReducer,
} from './objetivesAbsencesReducer'

import {
  objetiveGeneralRegisterReducer,
  objetiveGeneralListReducer,
  objetivesGeneralDeleteReducer,
  objetivesGeneralUpdateReducer,
} from './objetivesGeneralsReducer'

import {
  objetiveSpecificRegisterReducer,
  objetiveSpecificListReducer,
  objetivesSpecificDeleteReducer,
  objetivesSpecificUpdateReducer,
} from './objetivesSpecificsReducer'

import {
  objetiveOrdExtOtherRegisterReducer,
  objetiveOrdExtOtherListReducer,
  objetivesOrdExtDeleteReducer,
  objetivesOrdExtUpdateReducer,
  objetiveHistoricalListReducer,
} from './objetivesOrdExtOtherReducer'

import {
  myObjetiveListReducer,
} from './myObjetivesReducer'

import { entriesToManagerListReducer, entriesToManagerRegisterReducer } from './entriesManagerReducer'
import {
  entriesDeleteReducer,
  entriesListReducer,
  entriesListByManagerIdReducer,
  entriesListByTaskIdReducer,
  entriesRegisterReducer,
  entriesUpdateReducer,
} from './entriesReducer'

import {
  dificultiesDeleteReducer,
  dificultiesListReducer,
  dificultiesListByManagerIdReducer,
  dificultiesListByTaskIdReducer,
  dificultiesRegisterReducer,
  dificultiesUpdateReducer,
} from './dificultiesReducer'

import { difficultiesToManagerListReducer, difficultiesToManagerRegisterReducer } from './difficultiesManagerReducer'
import { difficultiesDeleteReducer, difficultiesListReducer } from './difficultiesReducer'
import { 
  sharedRegisterReducer,
  sharedListReducer,
  sharedUpdateReducer,
  sharedDeleteReducer,
  sharedListByTaskIdReducer,
  getTasksSharedReducer,
} from './sharedReducer'

import { 
  acumulativesRegisterReducer,
  acumulativesListReducer,
  acumulativesDeleteReducer,
  acumulativesTasksSelectReducer,
  acumulativesTasksHijaSelectReducer,
  acumulativesListByTaskIdReducer,
} from './acumulativesReducer'

export default combineReducers({  
  dashboardList: dashboardReducer,
  entriesUpdate: entriesUpdateReducer,
  entriesListByTaskId: entriesListByTaskIdReducer,
  entriesRegister: entriesRegisterReducer,
  entriesListByManagerId: entriesListByManagerIdReducer,
  evaluacionInfo: evaluacionInfoReducer,
  evaluacionCurrent: evaluacionCurrentReducer,
  evaluacionAgregado: evaluacionAgregadoReducer,
  evaluacionResumen: evaluacionResumenReducer,
  evaluacionCalculo: evaluacionCalculoReducer,
  evaluacionCorreccionUpdate: evaluacionCorreccionUpdateReducer,
  evaluacionCorreccionDelete: evaluacionCorreccionDeleteReducer,
  evaluacionCorreccionGlobalUpdate: evaluacionCorreccionGlobalUpdateReducer,
  evaluacionCorreccionGlobalDelete: evaluacionCorreccionGlobalDeleteReducer,
  evaluacionValidacionUpdate: evaluacionValidacionUpdateReducer,
  evaluacionSupervisionUpdate: evaluacionSupervisionUpdateReducer,
  evaluacionValidacionUpdate: evaluacionValidacionUpdateReducer,
  evaluacionSupervisionUpdate: evaluacionSupervisionUpdateReducer,
  evaluacionSupervisionMasiva: evaluacionSupervisionMasivaReducer,
  evaluacionValidacionMasiva: evaluacionValidacionMasivaReducer,
  evaluacionFinalizarSupervision: evaluacionFinalizarSupervisionReducer,
  evaluacionFinalizarValidacion: evaluacionFinalizarValidacionReducer,
  evaluacionInfoInforme: evaluacionInfoInformeReducer,
  evaluacionResumenInforme: evaluacionResumenInformeReducer,
  activitiesList: activitiesListReducer,
  activityInfo: activityInfoReducer,
  activitiesUpdate: activitiesUpdateReducer,
  activitiesDelete: activitiesDeleteReducer,
  activitiesListByJobPositionId: activitiesListByJobPositionIdReducer,
  departamentDelete: departamentDeleteReducer,
  departamentList: departamentListReducer,
  departamentRegister: departamentRegisterReducer,
  departamentUpdate: departamentUpdateReducer,
  departamentRelatedList: departamentRelatedListReducer,
  handleDuplicateTask: handleDuplicateTaskReducer,
  logDelete: logDeleteReducer,
  logDeleteMany: logDeleteManyReducer,
  logDetails: logDetailsReducer,
  logList: logListReducer,
  logRegister: logRegisterReducer,
  permissionDelete: permissionDeleteReducer,
  permissionList: permissionListReducer,
  permissionRegister: permissionRegisterReducer,
  permissionUpdate: permissionUpdateReducer,
  profileDelete: profileDeleteReducer,
  profileList: profileListReducer,
  profileRegister: profileRegisterReducer,
  profileToManagerDelete: profileToManagerDeleteReducer,
  profileToManagerList: profileToManagerListReducer,
  profileToManagerRegister: profileToManagerRegisterReducer,
  profileToManagerUpdate: profileToManagerUpdateReducer,
  profileUpdate: profileUpdateReducer,
  profileByPositionList: profileByPositionListReducer,
  refreshToken: refreshTokenReducer,
  roleDelete: roleDeleteReducer,
  roleList: roleListReducer,
  roleRegister: roleRegisterReducer,
  roleUpdate: roleUpdateReducer,
  roleRelatedList: roleRelatedListReducer,
  sendEMail: sendEMailReducer,
  serviceDelete: serviceDeleteReducer,
  serviceList: serviceListReducer,
  serviceRegister: serviceRegisterReducer,
  serviceUpdate: serviceUpdateReducer,
  serviceRelatedList: serviceRelatedListReducer,
  subdirectionDelete: subdirectionDeleteReducer,
  subdirectionList: subdirectionListReducer,
  subdirectionRegister: subdirectionRegisterReducer,
  subdirectionUpdate: subdirectionUpdateReducer,
  subdirectionRelatedList: subdirectionRelatedListReducer,
  taskAbsenceDelete: taskAbsenceDeleteReducer,
  taskAbsenceList: taskAbsenceListReducer,
  taskAbsenceRegister: taskAbsenceRegisterReducer,
  taskAbsenceUpdate: taskAbsenceUpdateReducer,
  taskDelete: taskDeleteReducer,
  taskGeneralDelete: taskGeneralDeleteReducer,
  taskGeneralList: taskGeneralListReducer,
  taskGeneralRegister: taskGeneralRegisterReducer,
  taskGeneralUpdate: taskGeneralUpdateReducer,
  taskList: taskListReducer,
  taskListByProfile: taskListByProfileReducer,
  taskOtherDelete: taskOtherDeleteReducer,
  taskOtherList: taskOtherListReducer,
  taskOtherRegister: taskOtherRegisterReducer,
  taskOtherUpdate: taskOtherUpdateReducer,
  taskProfiles: taskProfilesReducer,
  taskHistoricalList: taskHistoricalListReducer,
  taskRegister: taskRegisterReducer,
  taskSpecificDelete: taskSpecificDeleteReducer,
  taskSpecificList: taskSpecificListReducer,
  taskSpecificRegister: taskSpecificRegisterReducer,
  taskSpecificUpdate: taskSpecificUpdateReducer,
  taskSpecificByUser: taskSpecificByUserReducer,
  taskTypeDelete: taskTypeDeleteReducer,
  taskTypeList: taskTypeListReducer,
  taskTypeRegister: taskTypeRegisterReducer,
  taskTypeUpdate: taskTypeUpdateReducer,
  taskUpdate: taskUpdateReducer,
  teamWorkDelete: teamWorkDeleteReducer,
  teamWorkUpdate: teamWorkUpdateReducer,
  teamWorkList: teamWorkListReducer,
  teamWorkListByRole: teamWorkListByRoleReducer,
  teamWorkRegisterByResponsible: teamWorkRegisterByResponsibleReducer,
  teamWorkRegisterByPermission: teamWorkRegisterByPermissionReducer,
  teamWorkRegisterByValidator: teamWorkRegisterByValidatorReducer,
  teamWorksByResponsible: teamWorksByResponsibleReducer,
  teamWorksByValidator: teamWorksByValidatorReducer,
  teamWorkHistoricalList: teamWorkHistoricalListReducer,
  uiMultiTask: uiMultiTaskReducer,
  unitDelete: unitDeleteReducer,
  unitList: unitListReducer,
  unitRegister: unitRegisterReducer,
  unitUpdate: unitUpdateReducer,
  unitRelatedList: unitRelatedListReducer,
  festivosDelete: festivosDeleteReducer,
  festivosList: festivosListReducer,
  festivosRegister: festivosRegisterReducer,
  festivosUpdate: festivosUpdateReducer,
  configuracionDelete: configuracionDeleteReducer,
  configuracionList: configuracionListReducer,
  configuracionRegister: configuracionRegisterReducer,
  configuracionUpdate: configuracionUpdateReducer,
  configuracionHistoricalList: configuracionHistoricalListReducer,
  userDelete: userDeleteReducer,
  userDetails: userDetailsReducer,
  userList: userListReducer,
  userListByRoleName: userListByRoleNameReducer,
  userListResponsibles: userListResponsiblesReducer,
  userListValidators: userListValidatorsReducer,
  userLogin: userLoginReducer,
  userPermissionDelete: userPermissionDeleteReducer,
  userPermissionList: userPermissionListReducer,
  userPermissionRegister: userPermissionRegisterReducer,
  userPermissionUpdate: userPermissionUpdateReducer,
  userProfileInfo: userGetProfileInfoeReducer,
  userListByProfileId: userListByProfileIdReducer,
  userRegister: userRegisterReducer,
  userAvisos: userAvisosReducer,
  userUpdate: userUpdateReducer,
  userGetFavorites: userGetFavoritesReducer,
  userRegisterFavorites: userRegisterFavoritesReducer,
  taskById: taskByIdReducer,
  activitiesRegister: activitiesRegisterReducer,
  objetiveAbsenceRegister: objetiveAbsenceRegisterReducer,
  objetiveAbsenceList: objetivesAbsencesListReducer,
  objetivesAbsencesDelete: objetivesAbsencesDeleteReducer,
  objetivesAbsencesUpdate: objetivesAbsencesUpdateReducer,
  objetiveGeneralRegister: objetiveGeneralRegisterReducer,
  objetiveGeneralList: objetiveGeneralListReducer,
  objetivesGeneralDelete: objetivesGeneralDeleteReducer,
  objetivesGeneralUpdate: objetivesGeneralUpdateReducer,
  objetiveSpecificRegister: objetiveSpecificRegisterReducer,
  objetiveSpecificList: objetiveSpecificListReducer,
  objetivesSpecificDelete: objetivesSpecificDeleteReducer,
  objetivesSpecificUpdate: objetivesSpecificUpdateReducer,
  objetiveOrdExtOtherRegister: objetiveOrdExtOtherRegisterReducer,
  objetiveOrdExtOtherList: objetiveOrdExtOtherListReducer,
  objetiveHistoricalList: objetiveHistoricalListReducer,
  myObjetiveList: myObjetiveListReducer,
  objetivesOrdExtDelete: objetivesOrdExtDeleteReducer,
  objetivesOrdExtUpdate: objetivesOrdExtUpdateReducer,
  entriesToManagerList: entriesToManagerListReducer,
  entriesToManagerRegister: entriesToManagerRegisterReducer,
  entriesList: entriesListReducer,
  entriesDelete: entriesDeleteReducer,
  dificultiesList: dificultiesListReducer,
  dificultiesDelete: dificultiesDeleteReducer,
  dificultiesUpdate: dificultiesUpdateReducer,
  dificultiesListByTaskId: dificultiesListByTaskIdReducer,
  dificultiesRegister: dificultiesRegisterReducer,
  dificultiesListByManagerId: dificultiesListByManagerIdReducer,
  difficultiesList: difficultiesListReducer,
  difficultiesDelete: difficultiesDeleteReducer,
  difficultiesToManagerList: difficultiesToManagerListReducer,
  difficultiesToManagerRegister: difficultiesToManagerRegisterReducer,
  sharedRegister: sharedRegisterReducer,
  sharedList: sharedListReducer,
  sharedDelete: sharedDeleteReducer,
  sharedUpdate: sharedUpdateReducer,
  sharedListByTaskId: sharedListByTaskIdReducer,
  tasksShared: getTasksSharedReducer,
  acumulativesRegister: acumulativesRegisterReducer,
  acumulativesList: acumulativesListReducer,
  acumulativesDelete: acumulativesDeleteReducer,
  acumulativesTasksSelect: acumulativesTasksSelectReducer,
  acumulativesTasksHijaSelect: acumulativesTasksHijaSelectReducer,
  acumulativesListByTaskId: acumulativesListByTaskIdReducer,
})
