export const ACTIVITIES_LIST_REQUEST = 'ACTIVITIES_LIST_REQUEST'
export const ACTIVITIES_LIST_SUCCESS = 'ACTIVITIES_LIST_SUCCESS'
export const ACTIVITIES_LIST_FAIL = 'ACTIVITIES_LIST_FAIL'
export const ACTIVITIES_LIST_RESET = 'ACTIVITIES_LIST_RESET'

export const ACTIVITIES_INFO_REQUEST = 'ACTIVITIES_INFO_REQUEST'
export const ACTIVITIES_INFO_SUCCESS = 'ACTIVITIES_INFO_SUCCESS'
export const ACTIVITIES_INFO_FAIL = 'ACTIVITIES_INFO_FAIL'
export const ACTIVITIES_INFO_RESET = 'ACTIVITIES_INFO_RESET'

export const ACTIVITIES_REGISTER_REQUEST = 'ACTIVITIES_REGISTER_REQUEST'
export const ACTIVITIES_REGISTER_SUCCESS = 'ACTIVITIES_REGISTER_SUCCESS'
export const ACTIVITIES_REGISTER_FAIL = 'ACTIVITIES_REGISTER_FAIL'
export const ACTIVITIES_REGISTER_RESET = 'ACTIVITIES_REGISTER_RESET'

export const ACTIVITIES_UPDATE_REQUEST = 'ACTIVITIES_UPDATE_REQUEST'
export const ACTIVITIES_UPDATE_SUCCESS = 'ACTIVITIES_UPDATE_SUCCESS'
export const ACTIVITIES_UPDATE_FAIL = 'ACTIVITIES_UPDATE_FAIL'
export const ACTIVITIES_UPDATE_RESET = 'ACTIVITIES_UPDATE_RESET'

export const ACTIVITIES_DELETE_REQUEST = 'ACTIVITIES_DELETE_REQUEST'
export const ACTIVITIES_DELETE_SUCCESS = 'ACTIVITIES_DELETE_SUCCESS'
export const ACTIVITIES_DELETE_FAIL = 'ACTIVITIES_DELETE_FAIL'
export const ACTIVITIES_DELETE_RESET = 'ACTIVITIES_DELETE_RESET'

export const ACTIVITIES_LIST_BY_JOB_POSITION_ID_REQUEST = 'ACTIVITIES_LIST_BY_JOB_POSITION_ID_REQUEST'
export const ACTIVITIES_LIST_BY_JOB_POSITION_ID_SUCCESS = 'ACTIVITIES_LIST_BY_JOB_POSITION_ID_SUCCESS'
export const ACTIVITIES_LIST_BY_JOB_POSITION_ID_FAIL = 'ACTIVITIES_LIST_BY_JOB_POSITION_ID_FAIL'
export const ACTIVITIES_LIST_BY_JOB_POSITION_ID_RESET = 'ACTIVITIES_LIST_BY_JOB_POSITION_ID_RESET'
