export const ACUMULATIVES_REGISTER_REQUEST = 'ACUMULATIVES_REGISTER_REQUEST'
export const ACUMULATIVES_REGISTER_SUCCESS = 'ACUMULATIVES_REGISTER_SUCCESS'
export const ACUMULATIVES_REGISTER_FAIL = 'ACUMULATIVES_REGISTER_FAIL'
export const ACUMULATIVES_REGISTER_RESET = 'ACUMULATIVES_REGISTER_RESET'

export const ACUMULATIVES_LIST_REQUEST = 'ACUMULATIVES_LIST_REQUEST'
export const ACUMULATIVES_LIST_SUCCESS = 'ACUMULATIVES_LIST_SUCCESS'
export const ACUMULATIVES_LIST_FAIL = 'ACUMULATIVES_LIST_FAIL'
export const ACUMULATIVES_LIST_RESET = 'ACUMULATIVES_LIST_RESET'

export const ACUMULATIVES_DELETE_REQUEST = 'ACUMULATIVES_DELETE_REQUEST'
export const ACUMULATIVES_DELETE_SUCCESS = 'ACUMULATIVES_DELETE_SUCCESS'
export const ACUMULATIVES_DELETE_FAIL = 'ACUMULATIVES_DELETE_FAIL'
export const ACUMULATIVES_DELETE_RESET = 'ACUMULATIVES_DELETE_RESET'

export const ACUMULATIVES_LIST_BY_TASK_ID_REQUEST = 'ACUMULATIVES_LIST_BY_TASK_ID_REQUEST'
export const ACUMULATIVES_LIST_BY_TASK_ID_SUCCESS = 'ACUMULATIVES_LIST_BY_TASK_ID_SUCCESS'
export const ACUMULATIVES_LIST_BY_TASK_ID_FAIL = 'ACUMULATIVES_LIST_BY_TASK_ID_FAIL'
export const ACUMULATIVES_LIST_BY_TASK_ID_RESET = 'ACUMULATIVES_LIST_BY_TASK_ID_RESET'

export const ACUMULATIVES_TO_MANAGER_LIST_REQUEST = 'ACUMULATIVES_TO_MANAGER_LIST_REQUEST'
export const ACUMULATIVES_TO_MANAGER_LIST_SUCCESS = 'ACUMULATIVES_TO_MANAGER_LIST_SUCCESS'
export const ACUMULATIVES_TO_MANAGER_LIST_FAIL = 'ACUMULATIVES_TO_MANAGER_LIST_FAIL'
export const ACUMULATIVES_TO_MANAGER_LIST_RESET = 'ACUMULATIVES_TO_MANAGER_LIST_RESET'

export const ACUMULATIVES_HIJA_TO_MANAGER_LIST_REQUEST = 'ACUMULATIVES_HIJA_TO_MANAGER_LIST_REQUEST'
export const ACUMULATIVES_HIJA_TO_MANAGER_LIST_SUCCESS = 'ACUMULATIVES_HIJA_TO_MANAGER_LIST_SUCCESS'
export const ACUMULATIVES_HIJA_TO_MANAGER_LIST_FAIL = 'ACUMULATIVES_HIJA_TO_MANAGER_LIST_FAIL'
export const ACUMULATIVES_HIJA_TO_MANAGER_LIST_RESET = 'ACUMULATIVES_HIJA_TO_MANAGER_LIST_RESET'