export const CONFIGURACION_REGISTER_REQUEST = 'CONFIGURACION_REGISTER_REQUEST'
export const CONFIGURACION_REGISTER_SUCCESS = 'CONFIGURACION_REGISTER_SUCCESS'
export const CONFIGURACION_REGISTER_FAIL = 'CONFIGURACION_REGISTER_FAIL'
export const CONFIGURACION_REGISTER_RESET = 'CONFIGURACION_REGISTER_RESET'

export const CONFIGURACION_LIST_REQUEST = 'CONFIGURACION_LIST_REQUEST'
export const CONFIGURACION_LIST_SUCCESS = 'CONFIGURACION_LIST_SUCCESS'
export const CONFIGURACION_LIST_FAIL = 'CONFIGURACION_LIST_FAIL'
export const CONFIGURACION_LIST_RESET = 'CONFIGURACION_LIST_RESET'

export const CONFIGURACION_UPDATE_REQUEST = 'CONFIGURACION_UPDATE_REQUEST'
export const CONFIGURACION_UPDATE_SUCCESS = 'CONFIGURACION_UPDATE_SUCCESS'
export const CONFIGURACION_UPDATE_FAIL = 'CONFIGURACION_UPDATE_FAIL'
export const CONFIGURACION_UPDATE_RESET = 'CONFIGURACION_UPDATE_RESET'

export const CONFIGURACION_DELETE_REQUEST = 'CONFIGURACION_DELETE_REQUEST'
export const CONFIGURACION_DELETE_SUCCESS = 'CONFIGURACION_DELETE_SUCCESS'
export const CONFIGURACION_DELETE_FAIL = 'CONFIGURACION_DELETE_FAIL'
export const CONFIGURACION_DELETE_RESET = 'CONFIGURACION_DELETE_RESET'

export const CONFIGURACION_HISTORICAL_REQUEST = 'CONFIGURACION_DELETE_REQUEST'
export const CONFIGURACION_HISTORICAL_SUCCESS = 'CONFIGURACION_DELETE_SUCCESS'
export const CONFIGURACION_HISTORICAL_FAIL = 'CONFIGURACION_DELETE_FAIL'
export const CONFIGURACION_HISTORICAL_RESET = 'CONFIGURACION_DELETE_RESET'
