export const DEPARTAMENT_REGISTER_REQUEST = 'DEPARTAMENT_REGISTER_REQUEST'
export const DEPARTAMENT_REGISTER_SUCCESS = 'DEPARTAMENT_REGISTER_SUCCESS'
export const DEPARTAMENT_REGISTER_FAIL = 'DEPARTAMENT_REGISTER_FAIL'
export const DEPARTAMENT_REGISTER_RESET = 'DEPARTAMENT_REGISTER_RESET'

export const DEPARTAMENT_LIST_REQUEST = 'DEPARTAMENT_LIST_REQUEST'
export const DEPARTAMENT_LIST_SUCCESS = 'DEPARTAMENT_LIST_SUCCESS'
export const DEPARTAMENT_LIST_FAIL = 'DEPARTAMENT_LIST_FAIL'
export const DEPARTAMENT_LIST_RESET = 'DEPARTAMENT_LIST_RESET'

export const DEPARTAMENT_UPDATE_REQUEST = 'DEPARTAMENT_UPDATE_REQUEST'
export const DEPARTAMENT_UPDATE_SUCCESS = 'DEPARTAMENT_UPDATE_SUCCESS'
export const DEPARTAMENT_UPDATE_FAIL = 'DEPARTAMENT_UPDATE_FAIL'
export const DEPARTAMENT_UPDATE_RESET = 'DEPARTAMENT_UPDATE_RESET'

export const DEPARTAMENT_DELETE_REQUEST = 'DEPARTAMENT_DELETE_REQUEST'
export const DEPARTAMENT_DELETE_SUCCESS = 'DEPARTAMENT_DELETE_SUCCESS'
export const DEPARTAMENT_DELETE_FAIL = 'DEPARTAMENT_DELETE_FAIL'
export const DEPARTAMENT_DELETE_RESET = 'DEPARTAMENT_DELETE_RESET'

export const DEPARTAMENT_RELATED_LIST_REQUEST = 'DEPARTAMENT_RELATED_LIST_REQUEST'
export const DEPARTAMENT_RELATED_LIST_SUCCESS = 'DEPARTAMENT_RELATED_LIST_SUCCESS'
export const DEPARTAMENT_RELATED_LIST_FAIL = 'DEPARTAMENT_RELATED_LIST_FAIL'
export const DEPARTAMENT_RELATED_LIST_RESET = 'DEPARTAMENT_RELATED_LIST_RESET'
