export const DIFFICULTIES_LIST_REQUEST = 'DIFFICULTIES_LIST_REQUEST'
export const DIFFICULTIES_LIST_SUCCESS = 'DIFFICULTIES_LIST_SUCCESS'
export const DIFFICULTIES_LIST_FAIL = 'DIFFICULTIES_LIST_FAIL'
export const DIFFICULTIES_LIST_RESET = 'DIFFICULTIES_LIST_RESET'

export const DIFFICULTIES_DELETE_REQUEST = 'DIFFICULTIES_DELETE_REQUEST'
export const DIFFICULTIES_DELETE_SUCCESS = 'DIFFICULTIES_DELETE_SUCCESS'
export const DIFFICULTIES_DELETE_FAIL = 'DIFFICULTIES_DELETE_FAIL'
export const DIFFICULTIES_DELETE_RESET = 'DIFFICULTIES_DELETE_RESET'
