export const DIFICULTIES_LIST_REQUEST = 'DIFICULTIES_LIST_REQUEST'
export const DIFICULTIES_LIST_SUCCESS = 'DIFICULTIES_LIST_SUCCESS'
export const DIFICULTIES_LIST_FAIL = 'DIFICULTIES_LIST_FAIL'
export const DIFICULTIES_LIST_RESET = 'DIFICULTIES_LIST_RESET'

export const DIFICULTIES_REGISTER_REQUEST = 'DIFICULTIES_REGISTER_REQUEST'
export const DIFICULTIES_REGISTER_SUCCESS = 'DIFICULTIES_REGISTER_SUCCESS'
export const DIFICULTIES_REGISTER_FAIL = 'DIFICULTIES_REGISTER_FAIL'
export const DIFICULTIES_REGISTER_RESET = 'DIFICULTIES_REGISTER_RESET'

export const DIFICULTIES_UPDATE_REQUEST = 'DIFICULTIES_UPDATE_REQUEST'
export const DIFICULTIES_UPDATE_SUCCESS = 'DIFICULTIES_UPDATE_SUCCESS'
export const DIFICULTIES_UPDATE_FAIL = 'DIFICULTIES_UPDATE_FAIL'
export const DIFICULTIES_UPDATE_RESET = 'DIFICULTIES_UPDATE_RESET'

export const DIFICULTIES_LIST_BY_MANAGER_ID_REQUEST = 'DIFICULTIES_LIST_BY_MANAGER_ID_REQUEST'
export const DIFICULTIES_LIST_BY_MANAGER_ID_SUCCESS = 'DIFICULTIES_LIST_BY_MANAGER_ID_SUCCESS'
export const DIFICULTIES_LIST_BY_MANAGER_ID_FAIL = 'DIFICULTIES_LIST_BY_MANAGER_ID_FAIL'
export const DIFICULTIES_LIST_BY_MANAGER_ID_RESET = 'DIFICULTIES_LIST_BY_MANAGER_ID_RESET'

export const DIFICULTIES_LIST_BY_TASK_ID_REQUEST = 'DIFICULTIES_LIST_BY_TASK_ID_REQUEST'
export const DIFICULTIES_LIST_BY_TASK_ID_SUCCESS = 'DIFICULTIES_LIST_BY_TASK_ID_SUCCESS'
export const DIFICULTIES_LIST_BY_TASK_ID_FAIL = 'DIFICULTIES_LIST_BY_TASK_ID_FAIL'
export const DIFICULTIES_LIST_BY_TASK_ID_RESET = 'DIFICULTIES_LIST_BY_TASK_ID_RESET'

export const DIFICULTIES_DELETE_REQUEST = 'DIFICULTIES_DELETE_REQUEST'
export const DIFICULTIES_DELETE_SUCCESS = 'DIFICULTIES_DELETE_SUCCESS'
export const DIFICULTIES_DELETE_FAIL = 'DIFICULTIES_DELETE_FAIL'
export const DIFICULTIES_DELETE_RESET = 'DIFICULTIES_DELETE_RESET'
