export const ENTRIES_TO_MANAGER_LIST_REQUEST = 'ENTRIES_TO_MANAGER_LIST_REQUEST'
export const ENTRIES_TO_MANAGER_LIST_SUCCESS = 'ENTRIES_TO_MANAGER_LIST_SUCCESS'
export const ENTRIES_TO_MANAGER_LIST_FAIL = 'ENTRIES_TO_MANAGER_LIST_FAIL'
export const ENTRIES_TO_MANAGER_LIST_RESET = 'ENTRIES_TO_MANAGER_LIST_RESET'
