export const ENTRIES_LIST_REQUEST = 'ENTRIES_LIST_REQUEST'
export const ENTRIES_LIST_SUCCESS = 'ENTRIES_LIST_SUCCESS'
export const ENTRIES_LIST_FAIL = 'ENTRIES_LIST_FAIL'
export const ENTRIES_LIST_RESET = 'ENTRIES_LIST_RESET'

export const ENTRIES_REGISTER_REQUEST = 'ENTRIES_REGISTER_REQUEST'
export const ENTRIES_REGISTER_SUCCESS = 'ENTRIES_REGISTER_SUCCESS'
export const ENTRIES_REGISTER_FAIL = 'ENTRIES_REGISTER_FAIL'
export const ENTRIES_REGISTER_RESET = 'ENTRIES_REGISTER_RESET'

export const ENTRIES_UPDATE_REQUEST = 'ENTRIES_UPDATE_REQUEST'
export const ENTRIES_UPDATE_SUCCESS = 'ENTRIES_UPDATE_SUCCESS'
export const ENTRIES_UPDATE_FAIL = 'ENTRIES_UPDATE_FAIL'
export const ENTRIES_UPDATE_RESET = 'ENTRIES_UPDATE_RESET'

export const ENTRIES_LIST_BY_MANAGER_ID_REQUEST = 'ENTRIES_LIST_BY_MANAGER_ID_REQUEST'
export const ENTRIES_LIST_BY_MANAGER_ID_SUCCESS = 'ENTRIES_LIST_BY_MANAGER_ID_SUCCESS'
export const ENTRIES_LIST_BY_MANAGER_ID_FAIL = 'ENTRIES_LIST_BY_MANAGER_ID_FAIL'
export const ENTRIES_LIST_BY_MANAGER_ID_RESET = 'ENTRIES_LIST_BY_MANAGER_ID_RESET'

export const ENTRIES_LIST_BY_TASK_ID_REQUEST = 'ENTRIES_LIST_BY_TASK_ID_REQUEST'
export const ENTRIES_LIST_BY_TASK_ID_SUCCESS = 'ENTRIES_LIST_BY_TASK_ID_SUCCESS'
export const ENTRIES_LIST_BY_TASK_ID_FAIL = 'ENTRIES_LIST_BY_TASK_ID_FAIL'
export const ENTRIES_LIST_BY_TASK_ID_RESET = 'ENTRIES_LIST_BY_TASK_ID_RESET'

export const ENTRIES_DELETE_REQUEST = 'ENTRIES_DELETE_REQUEST'
export const ENTRIES_DELETE_SUCCESS = 'ENTRIES_DELETE_SUCCESS'
export const ENTRIES_DELETE_FAIL = 'ENTRIES_DELETE_FAIL'
export const ENTRIES_DELETE_RESET = 'ENTRIES_DELETE_RESET'
