export const FESTIVOS_REGISTER_REQUEST = 'FESTIVOS_REGISTER_REQUEST'
export const FESTIVOS_REGISTER_SUCCESS = 'FESTIVOS_REGISTER_SUCCESS'
export const FESTIVOS_REGISTER_FAIL = 'FESTIVOS_REGISTER_FAIL'
export const FESTIVOS_REGISTER_RESET = 'FESTIVOS_REGISTER_RESET'

export const FESTIVOS_LIST_REQUEST = 'FESTIVOS_LIST_REQUEST'
export const FESTIVOS_LIST_SUCCESS = 'FESTIVOS_LIST_SUCCESS'
export const FESTIVOS_LIST_FAIL = 'FESTIVOS_LIST_FAIL'
export const FESTIVOS_LIST_RESET = 'FESTIVOS_LIST_RESET'

export const FESTIVOS_UPDATE_REQUEST = 'FESTIVOS_UPDATE_REQUEST'
export const FESTIVOS_UPDATE_SUCCESS = 'FESTIVOS_UPDATE_SUCCESS'
export const FESTIVOS_UPDATE_FAIL = 'FESTIVOS_UPDATE_FAIL'
export const FESTIVOS_UPDATE_RESET = 'FESTIVOS_UPDATE_RESET'

export const FESTIVOS_DELETE_REQUEST = 'FESTIVOS_DELETE_REQUEST'
export const FESTIVOS_DELETE_SUCCESS = 'FESTIVOS_DELETE_SUCCESS'
export const FESTIVOS_DELETE_FAIL = 'FESTIVOS_DELETE_FAIL'
export const FESTIVOS_DELETE_RESET = 'FESTIVOS_DELETE_RESET'
