export const INCOME_UPDATE_REQUEST = 'INCOME_UPDATE_REQUEST'
export const INCOME_UPDATE_SUCCESS = 'INCOME_UPDATE_SUCCESS'
export const INCOME_UPDATE_FAIL = 'INCOME_UPDATE_FAIL'
export const INCOME_UPDATE_RESET = 'INCOME_UPDATE_RESET'
