export const INVESTMENT_REGISTER_REQUEST = 'INVESTMENT_REGISTER_REQUEST'
export const INVESTMENT_REGISTER_SUCCESS = 'INVESTMENT_REGISTER_SUCCESS'
export const INVESTMENT_REGISTER_FAIL = 'INVESTMENT_REGISTER_FAIL'
export const INVESTMENT_REGISTER_RESET = 'INVESTMENT_REGISTER_RESET'

export const INVESTMENT_ANNULATION_REQUEST_REQUEST = 'INVESTMENT_ANNULATION_REQUEST_REQUEST'
export const INVESTMENT_ANNULATION_REQUEST_SUCCESS = 'INVESTMENT_ANNULATION_REQUEST_SUCCESS'
export const INVESTMENT_ANNULATION_REQUEST_FAIL = 'INVESTMENT_ANNULATION_REQUEST_FAIL'
export const INVESTMENT_ANNULATION_REQUEST_RESET = 'INVESTMENT_ANNULATION_REQUEST_RESET'

export const INVESTMENT_ADMIN_DECLINE_REQUEST = 'INVESTMENT_ADMIN_DECLINE_REQUEST'
export const INVESTMENT_ADMIN_DECLINE_SUCCESS = 'INVESTMENT_ADMIN_DECLINE_SUCCESS'
export const INVESTMENT_ADMIN_DECLINE_FAIL = 'INVESTMENT_ADMIN_DECLINE_FAIL'
export const INVESTMENT_ADMIN_DECLINE_RESET = 'INVESTMENT_ADMIN_DECLINE_RESET'

export const INVESTMENT_MY_LIST_REQUEST = 'INVESTMENT_MY_LIST_REQUEST'
export const INVESTMENT_MY_LIST_SUCCESS = 'INVESTMENT_MY_LIST_SUCCESS'
export const INVESTMENT_MY_LIST_FAIL = 'INVESTMENT_MY_LIST_FAIL'
export const INVESTMENT_MY_LIST_RESET = 'INVESTMENT_MY_LIST_RESET'

export const INVESTMENTS_BY_PROFILE_AND_PROJECT_REQUEST = 'INVESTMENTS_BY_PROFILE_AND_PROJECT_REQUEST'
export const INVESTMENTS_BY_PROFILE_AND_PROJECT_SUCCESS = 'INVESTMENTS_BY_PROFILE_AND_PROJECT_SUCCESS'
export const INVESTMENTS_BY_PROFILE_AND_PROJECT_FAIL = 'INVESTMENTS_BY_PROFILE_AND_PROJECT_FAIL'
export const INVESTMENTS_BY_PROFILE_AND_PROJECT_RESET = 'INVESTMENTS_BY_PROFILE_AND_PROJECT_RESET'

export const INVESTMENTS_BY_PROJECT_REQUEST = 'INVESTMENTS_BY_PROJECT_REQUEST'
export const INVESTMENTS_BY_PROJECT_SUCCESS = 'INVESTMENTS_BY_PROJECT_SUCCESS'
export const INVESTMENTS_BY_PROJECT_FAIL = 'INVESTMENTS_BY_PROJECT_FAIL'
export const INVESTMENTS_BY_PROJECT_RESET = 'INVESTMENTS_BY_PROJECT_RESET'

export const INVESTMENTS_BY_PROFILE_REQUEST = 'INVESTMENTS_BY_PROFILE_REQUEST'
export const INVESTMENTS_BY_PROFILE_SUCCESS = 'INVESTMENTS_BY_PROFILE_SUCCESS'
export const INVESTMENTS_BY_PROFILE_FAIL = 'INVESTMENTS_BY_PROFILE_FAIL'
export const INVESTMENTS_BY_PROFILE_RESET = 'INVESTMENTS_BY_PROFILE_RESET'

export const INVESTMENT_CANCELLATION_LIST_REQUEST = 'INVESTMENT_CANCELLATION_LIST_REQUEST'
export const INVESTMENT_CANCELLATION_LIST_SUCCESS = 'INVESTMENT_CANCELLATION_LIST_SUCCESS'
export const INVESTMENT_CANCELLATION_LIST_FAIL = 'INVESTMENT_CANCELLATION_LIST_FAIL'
export const INVESTMENT_CANCELLATION_LIST_RESET = 'INVESTMENT_CANCELLATION_LIST_RESET'

export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST'
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS'
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL'
export const INVESTMENT_LIST_RESET = 'INVESTMENT_LIST_RESET'

export const INVESTMENT_HISTORY_REQUEST = 'INVESTMENT_HISTORY_REQUEST'
export const INVESTMENT_HISTORY_SUCCESS = 'INVESTMENT_HISTORY_SUCCESS'
export const INVESTMENT_HISTORY_FAIL = 'INVESTMENT_HISTORY_FAIL'
export const INVESTMENT_HISTORY_RESET = 'INVESTMENT_HISTORY_RESET'
