export const INVESTOR_PROFILE_REGISTER_REQUEST = 'INVESTOR_PROFILE_REGISTER_REQUEST'
export const INVESTOR_PROFILE_REGISTER_SUCCESS = 'INVESTOR_PROFILE_REGISTER_SUCCESS'
export const INVESTOR_PROFILE_REGISTER_FAIL = 'INVESTOR_PROFILE_REGISTER_FAIL'
export const INVESTOR_PROFILE_REGISTER_RESET = 'INVESTOR_PROFILE_REGISTER_RESET'

export const INVESTORS_PROFILE_BY_USER_REQUEST = 'INVESTORS_PROFILE_BY_USER_REQUEST'
export const INVESTORS_PROFILE_BY_USER_SUCCESS = 'INVESTORS_PROFILE_BY_USER_SUCCESS'
export const INVESTORS_PROFILE_BY_USER_FAIL = 'INVESTORS_PROFILE_BY_USER_FAIL'
export const INVESTORS_PROFILE_BY_USER_RESET = 'INVESTORS_PROFILE_BY_USER_RESET'

export const INVESTOR_PROFILE_UPDATE_REQUEST = 'INVESTOR_PROFILE_UPDATE_REQUEST'
export const INVESTOR_PROFILE_UPDATE_SUCCESS = 'INVESTOR_PROFILE_UPDATE_SUCCESS'
export const INVESTOR_PROFILE_UPDATE_FAIL = 'INVESTOR_PROFILE_UPDATE_FAIL'
export const INVESTOR_PROFILE_UPDATE_RESET = 'INVESTOR_PROFILE_UPDATE_RESET'
