export const MY_OBJETIVES_LIST_REQUEST = 'MY_OBJETIVES_LIST_REQUEST'
export const MY_OBJETIVES_LIST_SUCCESS = 'MY_OBJETIVES_LIST_SUCCESS'
export const MY_OBJETIVES_LIST_FAIL = 'MY_OBJETIVES_LIST_FAIL'
export const MY_OBJETIVES_LIST_RESET = 'MY_OBJETIVES_LIST_RESET'