export const OBJETIVES_GENERAL_REGISTER_REQUEST = 'OBJETIVES_GENERAL_REGISTER_REQUEST'
export const OBJETIVES_GENERAL_REGISTER_SUCCESS = 'OBJETIVES_GENERAL_REGISTER_SUCCESS'
export const OBJETIVES_GENERAL_REGISTER_FAIL = 'OBJETIVES_GENERAL_REGISTER_FAIL'
export const OBJETIVES_GENERAL_REGISTER_RESET = 'OBJETIVES_GENERAL_REGISTER_RESET'

export const OBJETIVES_GENERAL_LIST_REQUEST = 'OBJETIVES_GENERAL_LIST_REQUEST'
export const OBJETIVES_GENERAL_LIST_SUCCESS = 'OBJETIVES_GENERAL_LIST_SUCCESS'
export const OBJETIVES_GENERAL_LIST_FAIL = 'OBJETIVES_GENERAL_LIST_FAIL'
export const OBJETIVES_GENERAL_LIST_RESET = 'OBJETIVES_GENERAL_LIST_RESET'

export const OBJETIVES_GENERAL_UPDATE_REQUEST = 'OBJETIVES_GENERAL_UPDATE_REQUEST'
export const OBJETIVES_GENERAL_UPDATE_SUCCESS = 'OBJETIVES_GENERAL_UPDATE_SUCCESS'
export const OBJETIVES_GENERAL_UPDATE_FAIL = 'OBJETIVES_GENERAL_UPDATE_FAIL'
export const OBJETIVES_GENERAL_UPDATE_RESET = 'OBJETIVES_GENERAL_UPDATE_RESET'

export const OBJETIVES_GENERAL_DELETE_REQUEST = 'OBJETIVES_GENERAL_DELETE_REQUEST'
export const OBJETIVES_GENERAL_DELETE_SUCCESS = 'OBJETIVES_GENERAL_DELETE_SUCCESS'
export const OBJETIVES_GENERAL_DELETE_FAIL = 'OBJETIVES_GENERAL_DELETE_FAIL'
export const OBJETIVES_GENERAL_DELETE_RESET = 'OBJETIVES_GENERAL_DELETE_RESET'
