export const PERMISSION_REGISTER_REQUEST = 'PERMISSION_REGISTER_REQUEST'
export const PERMISSION_REGISTER_SUCCESS = 'PERMISSION_REGISTER_SUCCESS'
export const PERMISSION_REGISTER_FAIL = 'PERMISSION_REGISTER_FAIL'
export const PERMISSION_REGISTER_RESET = 'PERMISSION_REGISTER_RESET'

export const PERMISSION_LIST_REQUEST = 'PERMISSION_LIST_REQUEST'
export const PERMISSION_LIST_SUCCESS = 'PERMISSION_LIST_SUCCESS'
export const PERMISSION_LIST_FAIL = 'PERMISSION_LIST_FAIL'
export const PERMISSION_LIST_RESET = 'PERMISSION_LIST_RESET'

export const PERMISSION_UPDATE_REQUEST = 'PERMISSION_UPDATE_REQUEST'
export const PERMISSION_UPDATE_SUCCESS = 'PERMISSION_UPDATE_SUCCESS'
export const PERMISSION_UPDATE_FAIL = 'PERMISSION_UPDATE_FAIL'
export const PERMISSION_UPDATE_RESET = 'PERMISSION_UPDATE_RESET'

export const PERMISSION_DELETE_REQUEST = 'PERMISSION_DELETE_REQUEST'
export const PERMISSION_DELETE_SUCCESS = 'PERMISSION_DELETE_SUCCESS'
export const PERMISSION_DELETE_FAIL = 'PERMISSION_DELETE_FAIL'
export const PERMISSION_DELETE_RESET = 'PERMISSION_DELETE_RESET'
