export const ROLE_REGISTER_REQUEST = 'ROLE_REGISTER_REQUEST'
export const ROLE_REGISTER_SUCCESS = 'ROLE_REGISTER_SUCCESS'
export const ROLE_REGISTER_FAIL = 'ROLE_REGISTER_FAIL'
export const ROLE_REGISTER_RESET = 'ROLE_REGISTER_RESET'

export const ROLE_LIST_REQUEST = 'ROLE_LIST_REQUEST'
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS'
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL'
export const ROLE_LIST_RESET = 'ROLE_LIST_RESET'

export const ROLE_UPDATE_REQUEST = 'ROLE_UPDATE_REQUEST'
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS'
export const ROLE_UPDATE_FAIL = 'ROLE_UPDATE_FAIL'
export const ROLE_UPDATE_RESET = 'ROLE_UPDATE_RESET'

export const ROLE_DELETE_REQUEST = 'ROLE_DELETE_REQUEST'
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS'
export const ROLE_DELETE_FAIL = 'ROLE_DELETE_FAIL'
export const ROLE_DELETE_RESET = 'ROLE_DELETE_RESET'

export const ROLE_RELATED_LIST_REQUEST = 'ROLE_RELATED_LIST_REQUEST'
export const ROLE_RELATED_LIST_SUCCESS = 'ROLE_RELATED_LIST_SUCCESS'
export const ROLE_RELATED_LIST_FAIL = 'ROLE_RELATED_LIST_FAIL'
export const ROLE_RELATED_LIST_RESET = 'ROLE_RELATED_LIST_RESET'
