export const SEND_MAIL_REQUEST = 'SEND_MAIL_REQUEST'
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS'
export const SEND_MAIL_FAIL = 'SEND_MAIL_FAIL'
export const SEND_MAIL_RESET = 'SEND_MAIL_RESET'
