export const SHARED_REGISTER_REQUEST = 'SHARED_REGISTER_REQUEST'
export const SHARED_REGISTER_SUCCESS = 'SHARED_REGISTER_SUCCESS'
export const SHARED_REGISTER_FAIL = 'SHARED_REGISTER_FAIL'
export const SHARED_REGISTER_RESET = 'SHARED_REGISTER_RESET'

export const SHARED_LIST_REQUEST = 'SHARED_LIST_REQUEST'
export const SHARED_LIST_SUCCESS = 'SHARED_LIST_SUCCESS'
export const SHARED_LIST_FAIL = 'SHARED_LIST_FAIL'
export const SHARED_LIST_RESET = 'SHARED_LIST_RESET'

export const SHARED_UPDATE_REQUEST = 'SHARED_UPDATE_REQUEST'
export const SHARED_UPDATE_SUCCESS = 'SHARED_UPDATE_SUCCESS'
export const SHARED_UPDATE_FAIL = 'SHARED_UPDATE_FAIL'
export const SHARED_UPDATE_RESET = 'SHARED_UPDATE_RESET'

export const SHARED_DELETE_REQUEST = 'SHARED_DELETE_REQUEST'
export const SHARED_DELETE_SUCCESS = 'SHARED_DELETE_SUCCESS'
export const SHARED_DELETE_FAIL = 'SHARED_DELETE_FAIL'
export const SHARED_DELETE_RESET = 'SHARED_DELETE_RESET'

export const SHARED_LIST_BY_TASK_ID_REQUEST = 'SHARED_LIST_BY_TASK_ID_REQUEST'
export const SHARED_LIST_BY_TASK_ID_SUCCESS = 'SHARED_LIST_BY_TASK_ID_SUCCESS'
export const SHARED_LIST_BY_TASK_ID_FAIL = 'SHARED_LIST_BY_TASK_ID_FAIL'
export const SHARED_LIST_BY_TASK_ID_RESET = 'SHARED_LIST_BY_TASK_ID_RESET'

export const SHARED_TO_MANAGER_LIST_REQUEST = 'SHARED_TO_MANAGER_LIST_REQUEST'
export const SHARED_TO_MANAGER_LIST_SUCCESS = 'SHARED_TO_MANAGER_LIST_SUCCESS'
export const SHARED_TO_MANAGER_LIST_FAIL = 'SHARED_TO_MANAGER_LIST_FAIL'
export const SHARED_TO_MANAGER_LIST_RESET = 'SHARED_TO_MANAGER_LIST_RESET'