export const SUBDIRECTION_REGISTER_REQUEST = 'SUBDIRECTION_REGISTER_REQUEST'
export const SUBDIRECTION_REGISTER_SUCCESS = 'SUBDIRECTION_REGISTER_SUCCESS'
export const SUBDIRECTION_REGISTER_FAIL = 'SUBDIRECTION_REGISTER_FAIL'
export const SUBDIRECTION_REGISTER_RESET = 'SUBDIRECTION_REGISTER_RESET'

export const SUBDIRECTION_LIST_REQUEST = 'SUBDIRECTION_LIST_REQUEST'
export const SUBDIRECTION_LIST_SUCCESS = 'SUBDIRECTION_LIST_SUCCESS'
export const SUBDIRECTION_LIST_FAIL = 'SUBDIRECTION_LIST_FAIL'
export const SUBDIRECTION_LIST_RESET = 'SUBDIRECTION_LIST_RESET'

export const SUBDIRECTION_UPDATE_REQUEST = 'SUBDIRECTION_UPDATE_REQUEST'
export const SUBDIRECTION_UPDATE_SUCCESS = 'SUBDIRECTION_UPDATE_SUCCESS'
export const SUBDIRECTION_UPDATE_FAIL = 'SUBDIRECTION_UPDATE_FAIL'
export const SUBDIRECTION_UPDATE_RESET = 'SUBDIRECTION_UPDATE_RESET'

export const SUBDIRECTION_DELETE_REQUEST = 'SUBDIRECTION_DELETE_REQUEST'
export const SUBDIRECTION_DELETE_SUCCESS = 'SUBDIRECTION_DELETE_SUCCESS'
export const SUBDIRECTION_DELETE_FAIL = 'SUBDIRECTION_DELETE_FAIL'
export const SUBDIRECTION_DELETE_RESET = 'SUBDIRECTION_DELETE_RESET'

export const SUBDIRECTION_RELATED_LIST_REQUEST = 'SUBDIRECTION_RELATED_LIST_REQUEST'
export const SUBDIRECTION_RELATED_LIST_SUCCESS = 'SUBDIRECTION_RELATED_LIST_SUCCESS'
export const SUBDIRECTION_RELATED_LIST_FAIL = 'SUBDIRECTION_RELATED_LIST_FAIL'
export const SUBDIRECTION_RELATED_LIST_RESET = 'SUBDIRECTION_RELATED_LIST_RESET'
