export const TASK_SPECIFIC_REGISTER_REQUEST = 'TASK_SPECIFIC_REGISTER_REQUEST'
export const TASK_SPECIFIC_REGISTER_SUCCESS = 'TASK_SPECIFIC_REGISTER_SUCCESS'
export const TASK_SPECIFIC_REGISTER_FAIL = 'TASK_SPECIFIC_REGISTER_FAIL'
export const TASK_SPECIFIC_REGISTER_RESET = 'TASK_SPECIFIC_REGISTER_RESET'

export const TASK_SPECIFIC_LIST_REQUEST = 'TASK_SPECIFIC_LIST_REQUEST'
export const TASK_SPECIFIC_LIST_SUCCESS = 'TASK_SPECIFIC_LIST_SUCCESS'
export const TASK_SPECIFIC_LIST_FAIL = 'TASK_SPECIFIC_LIST_FAIL'
export const TASK_SPECIFIC_LIST_RESET = 'TASK_SPECIFIC_LIST_RESET'

export const TASK_SPECIFIC_UPDATE_REQUEST = 'TASK_SPECIFIC_UPDATE_REQUEST'
export const TASK_SPECIFIC_UPDATE_SUCCESS = 'TASK_SPECIFIC_UPDATE_SUCCESS'
export const TASK_SPECIFIC_UPDATE_FAIL = 'TASK_SPECIFIC_UPDATE_FAIL'
export const TASK_SPECIFIC_UPDATE_RESET = 'TASK_SPECIFIC_UPDATE_RESET'

export const TASK_SPECIFIC_DELETE_REQUEST = 'TASK_SPECIFIC_DELETE_REQUEST'
export const TASK_SPECIFIC_DELETE_SUCCESS = 'TASK_SPECIFIC_DELETE_SUCCESS'
export const TASK_SPECIFIC_DELETE_FAIL = 'TASK_SPECIFIC_DELETE_FAIL'
export const TASK_SPECIFIC_DELETE_RESET = 'TASK_SPECIFIC_DELETE_RESET'

export const TASK_SPECIFIC_BY_USER_REQUEST = 'TASK_SPECIFIC_BY_USER_REQUEST'
export const TASK_SPECIFIC_BY_USER_SUCCESS = 'TASK_SPECIFIC_BY_USER_SUCCESS'
export const TASK_SPECIFIC_BY_USER_FAIL = 'TASK_SPECIFIC_BY_USER_FAIL'
export const TASK_SPECIFIC_BY_USER_RESET = 'TASK_SPECIFIC_BY_USER_RESET'
