export const TASK_GENERAL_REGISTER_REQUEST = 'TASK_GENERAL_REGISTER_REQUEST'
export const TASK_GENERAL_REGISTER_SUCCESS = 'TASK_GENERAL_REGISTER_SUCCESS'
export const TASK_GENERAL_REGISTER_FAIL = 'TASK_GENERAL_REGISTER_FAIL'
export const TASK_GENERAL_REGISTER_RESET = 'TASK_GENERAL_REGISTER_RESET'

export const TASK_GENERAL_LIST_REQUEST = 'TASK_GENERAL_LIST_REQUEST'
export const TASK_GENERAL_LIST_SUCCESS = 'TASK_GENERAL_LIST_SUCCESS'
export const TASK_GENERAL_LIST_FAIL = 'TASK_GENERAL_LIST_FAIL'
export const TASK_GENERAL_LIST_RESET = 'TASK_GENERAL_LIST_RESET'

export const TASK_GENERAL_UPDATE_REQUEST = 'TASK_GENERAL_UPDATE_REQUEST'
export const TASK_GENERAL_UPDATE_SUCCESS = 'TASK_GENERAL_UPDATE_SUCCESS'
export const TASK_GENERAL_UPDATE_FAIL = 'TASK_GENERAL_UPDATE_FAIL'
export const TASK_GENERAL_UPDATE_RESET = 'TASK_GENERAL_UPDATE_RESET'

export const TASK_GENERAL_DELETE_REQUEST = 'TASK_GENERAL_DELETE_REQUEST'
export const TASK_GENERAL_DELETE_SUCCESS = 'TASK_GENERAL_DELETE_SUCCESS'
export const TASK_GENERAL_DELETE_FAIL = 'TASK_GENERAL_DELETE_FAIL'
export const TASK_GENERAL_DELETE_RESET = 'TASK_GENERAL_DELETE_RESET'
