export const TASK_OTHER_REGISTER_REQUEST = 'TASK_OTHER_REGISTER_REQUEST'
export const TASK_OTHER_REGISTER_SUCCESS = 'TASK_OTHER_REGISTER_SUCCESS'
export const TASK_OTHER_REGISTER_FAIL = 'TASK_OTHER_REGISTER_FAIL'
export const TASK_OTHER_REGISTER_RESET = 'TASK_OTHER_REGISTER_RESET'

export const TASK_OTHER_LIST_REQUEST = 'TASK_OTHER_LIST_REQUEST'
export const TASK_OTHER_LIST_SUCCESS = 'TASK_OTHER_LIST_SUCCESS'
export const TASK_OTHER_LIST_FAIL = 'TASK_OTHER_LIST_FAIL'
export const TASK_OTHER_LIST_RESET = 'TASK_OTHER_LIST_RESET'

export const TASK_OTHER_UPDATE_REQUEST = 'TASK_OTHER_UPDATE_REQUEST'
export const TASK_OTHER_UPDATE_SUCCESS = 'TASK_OTHER_UPDATE_SUCCESS'
export const TASK_OTHER_UPDATE_FAIL = 'TASK_OTHER_UPDATE_FAIL'
export const TASK_OTHER_UPDATE_RESET = 'TASK_OTHER_UPDATE_RESET'

export const TASK_OTHER_DELETE_REQUEST = 'TASK_OTHER_DELETE_REQUEST'
export const TASK_OTHER_DELETE_SUCCESS = 'TASK_OTHER_DELETE_SUCCESS'
export const TASK_OTHER_DELETE_FAIL = 'TASK_OTHER_DELETE_FAIL'
export const TASK_OTHER_DELETE_RESET = 'TASK_OTHER_DELETE_RESET'

export const TASK_HISTORICAL_REQUEST = 'TASK_HISTORICAL_REQUEST'
export const TASK_HISTORICAL_SUCCESS = 'TASK_HISTORICAL_SUCCESS'
export const TASK_HISTORICAL_FAIL = 'TASK_HISTORICAL_FAIL'
export const TASK_HISTORICAL_RESET = 'TASK_HISTORICAL_RESET'

export const TASK_PROFILES_REQUEST = 'TASK_PROFILES_REQUEST'
export const TASK_PROFILES_SUCCESS = 'TASK_PROFILES_SUCCESS'
export const TASK_PROFILES_FAIL = 'TASK_PROFILES_FAIL'
export const TASK_PROFILES_RESET = 'TASK_PROFILES_RESET'
