export const TASK_ABSENCE_REGISTER_REQUEST = 'TASK_ABSENCE_REGISTER_REQUEST'
export const TASK_ABSENCE_REGISTER_SUCCESS = 'TASK_ABSENCE_REGISTER_SUCCESS'
export const TASK_ABSENCE_REGISTER_FAIL = 'TASK_ABSENCE_REGISTER_FAIL'
export const TASK_ABSENCE_REGISTER_RESET = 'TASK_ABSENCE_REGISTER_RESET'

export const TASK_ABSENCE_LIST_REQUEST = 'TASK_ABSENCE_LIST_REQUEST'
export const TASK_ABSENCE_LIST_SUCCESS = 'TASK_ABSENCE_LIST_SUCCESS'
export const TASK_ABSENCE_LIST_FAIL = 'TASK_ABSENCE_LIST_FAIL'
export const TASK_ABSENCE_LIST_RESET = 'TASK_ABSENCE_LIST_RESET'

export const TASK_ABSENCE_UPDATE_REQUEST = 'TASK_ABSENCE_UPDATE_REQUEST'
export const TASK_ABSENCE_UPDATE_SUCCESS = 'TASK_ABSENCE_UPDATE_SUCCESS'
export const TASK_ABSENCE_UPDATE_FAIL = 'TASK_ABSENCE_UPDATE_FAIL'
export const TASK_ABSENCE_UPDATE_RESET = 'TASK_ABSENCE_UPDATE_RESET'

export const TASK_ABSENCE_DELETE_REQUEST = 'TASK_ABSENCE_DELETE_REQUEST'
export const TASK_ABSENCE_DELETE_SUCCESS = 'TASK_ABSENCE_DELETE_SUCCESS'
export const TASK_ABSENCE_DELETE_FAIL = 'TASK_ABSENCE_DELETE_FAIL'
export const TASK_ABSENCE_DELETE_RESET = 'TASK_ABSENCE_DELETE_RESET'
