export const TASK_REGISTER_REQUEST = 'TASK_REGISTER_REQUEST'
export const TASK_REGISTER_SUCCESS = 'TASK_REGISTER_SUCCESS'
export const TASK_REGISTER_FAIL = 'TASK_REGISTER_FAIL'
export const TASK_REGISTER_RESET = 'TASK_REGISTER_RESET'

export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL'
export const TASK_LIST_RESET = 'TASK_LIST_RESET'

export const TASK_LIST_BY_PROFILE_ID_REQUEST = 'TASK_LIST_BY_PROFILE_ID_REQUEST'
export const TASK_LIST_BY_PROFILE_ID_SUCCESS = 'TASK_LIST_BY_PROFILE_ID_SUCCESS'
export const TASK_LIST_BY_PROFILE_ID_FAIL = 'TASK_LIST_BY_PROFILE_ID_FAIL'
export const TASK_LIST_BY_PROFILE_ID_RESET = 'TASK_LIST_BY_PROFILE_ID_RESET'

export const TASK_BY_ID_REQUEST = 'TASK_BY_ID_REQUEST'
export const TASK_BY_ID_SUCCESS = 'TASK_BY_ID_SUCCESS'
export const TASK_BY_ID_FAIL = 'TASK_BY_ID_FAIL'
export const TASK_BY_ID_RESET = 'TASK_BY_ID_RESET'

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST'
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS'
export const TASK_UPDATE_FAIL = 'TASK_UPDATE_FAIL'
export const TASK_UPDATE_RESET = 'TASK_UPDATE_RESET'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'
export const TASK_DELETE_RESET = 'TASK_DELETE_RESET'

export const TASK_LIST_DUPLICATE_BY_PROFILE_PUSH_ALL_TASK = 'TASK_LIST_DUPLICATE_BY_PROFILE_PUSH_ALL_TASK'
export const TASK_LIST_DUPLICATE_BY_PROFILE_PUSH_CREATE_TASK = 'TASK_LIST_DUPLICATE_BY_PROFILE_PUSH_CREATE_TASK'
export const TASK_LIST_DUPLICATE_BY_PROFILE_FILTER_CREATE_TASK = 'TASK_LIST_DUPLICATE_BY_PROFILE_FILTER_CREATE_TASK'
export const TASK_LIST_DUPLICATE_BY_PROFILE_PUSH_DUPLICATE_TASK = 'TASK_LIST_DUPLICATE_BY_PROFILE_PUSH_DUPLICATE_TASK'
export const TASK_LIST_DUPLICATE_BY_PROFILE_FILTER_DUPLICATE_TASK =
  'TASK_LIST_DUPLICATE_BY_PROFILE_FILTER_DUPLICATE_TASK'
export const TASK_LIST_DUPLICATE_BY_PROFILE_MODIFY_TASK = 'TASK_LIST_DUPLICATE_BY_PROFILE_MODIFY_TASK'
export const TASK_LIST_DUPLICATE_BY_PROFILE_CLEAN = 'TASK_LIST_DUPLICATE_BY_PROFILE_CLEAN'
