export const TEAM_WORK_REGISTER_BY_RESPONSIBLE_REQUEST = 'TEAM_WORK_REGISTER_BY_RESPONSIBLE_REQUEST'
export const TEAM_WORK_REGISTER_BY_RESPONSIBLE_SUCCESS = 'TEAM_WORK_REGISTER_BY_RESPONSIBLE_SUCCESS'
export const TEAM_WORK_REGISTER_BY_RESPONSIBLE_FAIL = 'TEAM_WORK_REGISTER_BY_RESPONSIBLE_FAIL'
export const TEAM_WORK_REGISTER_BY_RESPONSIBLE_RESET = 'TEAM_WORK_REGISTER_BY_RESPONSIBLE_RESET'

export const TEAM_WORK_REGISTER_BY_PERMISSION_REQUEST = 'TEAM_WORK_REGISTER_BY_PERMISSION_REQUEST'
export const TEAM_WORK_REGISTER_BY_PERMISSION_SUCCESS = 'TEAM_WORK_REGISTER_BY_PERMISSION_SUCCESS'
export const TEAM_WORK_REGISTER_BY_PERMISSION_FAIL = 'TEAM_WORK_REGISTER_BY_PERMISSION_FAIL'
export const TEAM_WORK_REGISTER_BY_PERMISSION_RESET = 'TEAM_WORK_REGISTER_BY_PERMISSION_RESET'

export const TEAM_WORK_REGISTER_BY_VALIDATOR_REQUEST = 'TEAM_WORK_REGISTER_BY_VALIDATOR_REQUEST'
export const TEAM_WORK_REGISTER_BY_VALIDATOR_SUCCESS = 'TEAM_WORK_REGISTER_BY_VALIDATOR_SUCCESS'
export const TEAM_WORK_REGISTER_BY_VALIDATOR_FAIL = 'TEAM_WORK_REGISTER_BY_VALIDATOR_FAIL'
export const TEAM_WORK_REGISTER_BY_VALIDATOR_RESET = 'TEAM_WORK_REGISTER_BY_VALIDATOR_RESET'

export const TEAM_WORK_LIST_REQUEST = 'TEAM_WORK_LIST_REQUEST'
export const TEAM_WORK_LIST_SUCCESS = 'TEAM_WORK_LIST_SUCCESS'
export const TEAM_WORK_LIST_FAIL = 'TEAM_WORK_LIST_FAIL'
export const TEAM_WORK_LIST_RESET = 'TEAM_WORK_LIST_RESET'

export const TEAM_WORK_LIST_BY_ROLE_REQUEST = 'TEAM_WORK_LIST_BY_ROLE_REQUEST'
export const TEAM_WORK_LIST_BY_ROLE_SUCCESS = 'TEAM_WORK_LIST_BY_ROLE_SUCCESS'
export const TEAM_WORK_LIST_BY_ROLE_FAIL = 'TEAM_WORK_LIST_BY_ROLE_FAIL'
export const TEAM_WORK_LIST_BY_ROLE_RESET = 'TEAM_WORK_LIST_BY_ROLE_RESET'

export const TEAM_WORKS_BY_RESPONSIBLE_REQUEST = 'TEAM_WORKS_BY_RESPONSIBLE_REQUEST'
export const TEAM_WORKS_BY_RESPONSIBLE_SUCCESS = 'TEAM_WORKS_BY_RESPONSIBLE_SUCCESS'
export const TEAM_WORKS_BY_RESPONSIBLE_FAIL = 'TEAM_WORKS_BY_RESPONSIBLE_FAIL'
export const TEAM_WORKS_BY_RESPONSIBLE_RESET = 'TEAM_WORKS_BY_RESPONSIBLE_RESET'

export const TEAM_WORKS_BY_VALIDATOR_REQUEST = 'TEAM_WORKS_BY_VALIDATOR_REQUEST'
export const TEAM_WORKS_BY_VALIDATOR_SUCCESS = 'TEAM_WORKS_BY_VALIDATOR_SUCCESS'
export const TEAM_WORKS_BY_VALIDATOR_FAIL = 'TEAM_WORKS_BY_VALIDATOR_FAIL'
export const TEAM_WORKS_BY_VALIDATOR_RESET = 'TEAM_WORKS_BY_VALIDATOR_RESET'

export const TEAM_WORK_UPDATE_REQUEST = 'TEAM_WORK_UPDATE_REQUEST'
export const TEAM_WORK_UPDATE_SUCCESS = 'TEAM_WORK_UPDATE_SUCCESS'
export const TEAM_WORK_UPDATE_FAIL = 'TEAM_WORK_UPDATE_FAIL'
export const TEAM_WORK_UPDATE_RESET = 'TEAM_WORK_UPDATE_RESET'

export const TEAM_WORK_DELETE_REQUEST = 'TEAM_WORK_DELETE_REQUEST'
export const TEAM_WORK_DELETE_SUCCESS = 'TEAM_WORK_DELETE_SUCCESS'
export const TEAM_WORK_DELETE_FAIL = 'TEAM_WORK_DELETE_FAIL'
export const TEAM_WORK_DELETE_RESET = 'TEAM_WORK_DELETE_RESET'

export const TEAM_WORK_HISTORICAL_REQUEST = 'TEAM_WORK_HISTORICAL_REQUEST'
export const TEAM_WORK_HISTORICAL_SUCCESS = 'TEAM_WORK_HISTORICAL_SUCCESS'
export const TEAM_WORK_HISTORICAL_FAIL = 'TEAM_WORK_HISTORICAL_FAIL'
export const TEAM_WORK_HISTORICAL_RESET = 'TEAM_WORK_HISTORICAL_RESET'