export const UNIT_REGISTER_REQUEST = 'UNIT_REGISTER_REQUEST'
export const UNIT_REGISTER_SUCCESS = 'UNIT_REGISTER_SUCCESS'
export const UNIT_REGISTER_FAIL = 'UNIT_REGISTER_FAIL'
export const UNIT_REGISTER_RESET = 'UNIT_REGISTER_RESET'

export const UNIT_LIST_REQUEST = 'UNIT_LIST_REQUEST'
export const UNIT_LIST_SUCCESS = 'UNIT_LIST_SUCCESS'
export const UNIT_LIST_FAIL = 'UNIT_LIST_FAIL'
export const UNIT_LIST_RESET = 'UNIT_LIST_RESET'

export const UNIT_UPDATE_REQUEST = 'UNIT_UPDATE_REQUEST'
export const UNIT_UPDATE_SUCCESS = 'UNIT_UPDATE_SUCCESS'
export const UNIT_UPDATE_FAIL = 'UNIT_UPDATE_FAIL'
export const UNIT_UPDATE_RESET = 'UNIT_UPDATE_RESET'

export const UNIT_DELETE_REQUEST = 'UNIT_DELETE_REQUEST'
export const UNIT_DELETE_SUCCESS = 'UNIT_DELETE_SUCCESS'
export const UNIT_DELETE_FAIL = 'UNIT_DELETE_FAIL'
export const UNIT_DELETE_RESET = 'UNIT_DELETE_RESET'

export const UNIT_RELATED_LIST_REQUEST = 'UNIT_LIST_REQUEST'
export const UNIT_RELATED_LIST_SUCCESS = 'UNIT_LIST_SUCCESS'
export const UNIT_RELATED_LIST_FAIL = 'UNIT_LIST_FAIL'
export const UNIT_RELATED_LIST_RESET = 'UNIT_LIST_RESET'
