export const USER_PERMISSION_REGISTER_REQUEST = 'USER_PERMISSION_REGISTER_REQUEST'
export const USER_PERMISSION_REGISTER_SUCCESS = 'USER_PERMISSION_REGISTER_SUCCESS'
export const USER_PERMISSION_REGISTER_FAIL = 'USER_PERMISSION_REGISTER_FAIL'
export const USER_PERMISSION_REGISTER_RESET = 'USER_PERMISSION_REGISTER_RESET'

export const USER_PERMISSION_LIST_REQUEST = 'USER_PERMISSION_LIST_REQUEST'
export const USER_PERMISSION_LIST_SUCCESS = 'USER_PERMISSION_LIST_SUCCESS'
export const USER_PERMISSION_LIST_FAIL = 'USER_PERMISSION_LIST_FAIL'
export const USER_PERMISSION_LIST_RESET = 'USER_PERMISSION_LIST_RESET'

export const USER_PERMISSION_UPDATE_REQUEST = 'USER_PERMISSION_UPDATE_REQUEST'
export const USER_PERMISSION_UPDATE_SUCCESS = 'USER_PERMISSION_UPDATE_SUCCESS'
export const USER_PERMISSION_UPDATE_FAIL = 'USER_PERMISSION_UPDATE_FAIL'
export const USER_PERMISSION_UPDATE_RESET = 'USER_PERMISSION_UPDATE_RESET'

export const USER_PERMISSION_DELETE_REQUEST = 'USER_PERMISSION_DELETE_REQUEST'
export const USER_PERMISSION_DELETE_SUCCESS = 'USER_PERMISSION_DELETE_SUCCESS'
export const USER_PERMISSION_DELETE_FAIL = 'USER_PERMISSION_DELETE_FAIL'
export const USER_PERMISSION_DELETE_RESET = 'USER_PERMISSION_DELETE_RESET'
