export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_AVISOS_REQUEST = 'USER_AVISOS_REQUEST'
export const USER_AVISOS_SUCCESS = 'USER_AVISOS_SUCCESS'
export const USER_AVISOS_FAIL = 'USER_AVISOS_FAIL'
export const USER_AVISOS_RESET = 'USER_AVISOS_RESET'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'

export const USER_REFRESH_TOKEN_REQUEST = 'USER_REFRESH_TOKEN_REQUEST'
export const USER_REFRESH_TOKEN_SUCCESS = 'USER_REFRESH_TOKEN_SUCCESS'
export const USER_REFRESH_TOKEN_FAIL = 'USER_REFRESH_TOKEN_FAIL'
export const USER_REFRESH_TOKEN_RESET = 'USER_REFRESH_TOKEN_RESET'

export const USER_LIST_BY_ROLE_NAME_REQUEST = 'USER_LIST_BY_ROLE_NAME_REQUEST'
export const USER_LIST_BY_ROLE_NAME_SUCCESS = 'USER_LIST_BY_ROLE_NAME_SUCCESS'
export const USER_LIST_BY_ROLE_NAME_FAIL = 'USER_LIST_BY_ROLE_NAME_FAIL'
export const USER_LIST_BY_ROLE_NAME_RESET = 'USER_LIST_BY_ROLE_NAME_RESET'

export const USER_LIST_BY_PROFILE_ID_REQUEST = 'USER_LIST_BY_PROFILE_ID_REQUEST'
export const USER_LIST_BY_PROFILE_ID_SUCCESS = 'USER_LIST_BY_PROFILE_ID_SUCCESS'
export const USER_LIST_BY_PROFILE_ID_FAIL = 'USER_LIST_BY_PROFILE_ID_FAIL'
export const USER_LIST_BY_PROFILE_ID_RESET = 'USER_LIST_BY_PROFILE_ID_RESET'

export const USER_RESPONSIBLES_LIST_REQUEST = 'USER_RESPONSIBLES_LIST_REQUEST'
export const USER_RESPONSIBLES_LIST_SUCCESS = 'USER_RESPONSIBLES_LIST_SUCCESS'
export const USER_RESPONSIBLES_LIST_FAIL = 'USER_RESPONSIBLES_LIST_FAIL'
export const USER_RESPONSIBLES_LIST_RESET = 'USER_RESPONSIBLES_LIST_RESET'

export const USER_VALIDATORS_LIST_REQUEST = 'USER_VALIDATORS_LIST_REQUEST'
export const USER_VALIDATORS_LIST_SUCCESS = 'USER_VALIDATORS_LIST_SUCCESS'
export const USER_VALIDATORS_LIST_FAIL = 'USER_VALIDATORS_LIST_FAIL'
export const USER_VALIDATORS_LIST_RESET = 'USER_VALIDATORS_LIST_RESET'

export const USER_PROFILE_INFO_REQUEST = 'USER_PROFILE_INFO_REQUEST'
export const USER_PROFILE_INFO_SUCCESS = 'USER_PROFILE_INFO_SUCCESS'
export const USER_PROFILE_INFO_FAIL = 'USER_PROFILE_INFO_FAIL'
export const USER_PROFILE_INFO_RESET = 'USER_PROFILE_INFO_RESET'

export const USER_GET_FAVORITES_REQUEST = 'USER_GET_FAVORITES_REQUEST'
export const USER_GET_FAVORITES_SUCCESS = 'USER_GET_FAVORITES_SUCCESS'
export const USER_GET_FAVORITES_FAIL = 'USER_GET_FAVORITES_FAIL'
export const USER_GET_FAVORITES_RESET = 'USER_GET_FAVORITES_RESET'

export const USER_REGISTER_FAVORITES_REQUEST = 'USER_REGISTER_FAVORITES_REQUEST'
export const USER_REGISTER_FAVORITES_SUCCESS = 'USER_REGISTER_FAVORITES_SUCCESS'
export const USER_REGISTER_FAVORITES_FAIL = 'USER_REGISTER_FAVORITES_FAIL'
export const USER_REGISTER_FAVORITES_RESET = 'USER_REGISTER_FAVORITES_RESET'